FROM grycap/jenkins:docker
LABEL description="Alpine container with node and npm packages"
MAINTAINER Alfonso Pérez (alpegon3@upv.es)

# Update and install all the necessary packages
RUN apk add --no-cache nodejs nodejs-npm
