#!groovy
node {
    stage 'Checkout Git'
    git url: 'https://github.com/grycap/RADL'

    stage 'Launch Unit Tests'
    node('docker') {
        docker.image('grycap/jenkins:ubuntu14.04-python').inside {
            sh 'nosetests test/TestRADL.py --with-xunit --with-coverage --cover-erase --cover-html --cover-package=radl'
        }
    }

    stage 'Generate Packages'
    parallel 'centos6': {
        node('docker') {
            docker.image('grycap/jenkins:centos6-git').inside {
                sh 'sudo ./packages/generate_rpm.sh 1.el6'
                archive 'dist_pkg/*'
            }
        }
    }, 'centos7': {
        node('docker') {
            docker.image('grycap/jenkins:centos7-git').inside {
                sh 'sudo ./packages/generate_rpm.sh 1.el7'
                archive 'dist_pkg/*'
            }
        }
    }, 'ubuntu14.04': {
        node('docker') {
            docker.image('grycap/jenkins:ubuntu14.04-git').inside {
                sh 'sudo ./packages/generate_deb.sh'
                archive 'dist_pkg/*'
            }
        }
    },
    failFast: true
}
