node('lxc') {
    stage 'Check project'
    git url: 'https://github.com/indigo-dc/onedock.git'

    withEnv(['RAW_REPO_PATH=https://raw.githubusercontent.com/grycap/jenkins/master/config-scripts/onedock']) {

        stage 'Check for existing containers'
        sh 'curl -s $RAW_REPO_PATH/stop-destroy-existing-containers.sh | bash'
    
        stage 'Create lxc container'
        sh 'curl -s $RAW_REPO_PATH/create-lxc-container.sh | bash'
    
        stage 'Onedatastore test'
        sh 'curl -s $RAW_REPO_PATH/functional-tests/001-onedatastore-test.sh | bash'
    
        stage 'Oneimage test'
        sh 'curl -s $RAW_REPO_PATH/functional-tests/002-oneimage-test.sh | bash'
    
        stage 'Onevnet test'
        sh 'curl -s $RAW_REPO_PATH/functional-tests/003-onevnet-test.sh | bash'
    
        stage 'Onehost test'
        sh 'curl -s $RAW_REPO_PATH/functional-tests/004-onehost-test.sh | bash'
    
        stage 'Onevm test 1'
        sh 'curl -s $RAW_REPO_PATH/functional-tests/005-onevm-test.sh | bash'
    
        stage 'Onevm test 2'
        sh 'curl -s $RAW_REPO_PATH/functional-tests/006-onevm-test.sh | bash'
        
        stage 'Destroy existing containers'
        sh 'curl -s $RAW_REPO_PATH/stop-destroy-existing-containers.sh | bash'        
    }
}
