#!groovy

node('lxc') {
    stage 'Check project'
    git url: 'https://github.com/indigo-dc/onedock.git'

    withEnv(['TEST_REPO_PATH=https://raw.githubusercontent.com/indigo-dc/onedock/master/test']) {

        stage 'Check for existing containers'
        sh 'curl -s https://raw.githubusercontent.com/grycap/jenkins/master/config-scripts/onedock/stop-destroy-existing-containers.sh | bash -s one4test'

        stage 'Create lxc with one4 container'
        sh 'curl -s https://raw.githubusercontent.com/grycap/jenkins/master/config-scripts/onedock/create-lxc-container.sh | bash -s create-lxc one4test'

        stage 'Onedatastore test'
        sh 'curl -s $TEST_REPO_PATH/001-test-create-ds | bash'

        stage 'Oneimage test'
        sh 'curl -s $TEST_REPO_PATH/002-test-create-image | bash'

        stage 'Onevnet test'
        sh 'curl -s $TEST_REPO_PATH/003-test-create-network | bash'

        stage 'Onehost test'
        sh 'curl -s $TEST_REPO_PATH/004-test-create-host-one4 | bash'

        stage 'Onevm test 1'
        sh 'curl -s $TEST_REPO_PATH/005-test-create-vm-1 | bash'

        stage 'Onevm test 2'
        sh 'curl -s $TEST_REPO_PATH/006-test-create-vm-2 | bash'

        stage 'Destroy existing containers'
        sh 'curl -s https://raw.githubusercontent.com/grycap/jenkins/master/config-scripts/onedock/stop-destroy-existing-containers.sh | bash -s one4test'
    }

    stage 'Generate Packages'
    parallel 'centos7': {
        node('docker') {
            docker.image('grycap/jenkins:centos7-git').inside {
                git url: 'https://github.com/indigo-dc/onedock.git'
                sh 'cd packaging/rpm && ./build-rpm.sh -f ../../'
                archive 'packaging/rpm/dist/RPMS/noarch/*'
            }
        }
    }, 'ubuntu14.04': {
        node('docker') {
            docker.image('grycap/jenkins:ubuntu14.04-git').inside {
                git url: 'https://github.com/indigo-dc/onedock.git'
                sh 'cd packaging/debian && ./build-dev.sh -f ../../'
                archive 'packaging/debian/dist/*'
            }
        }
    },
    failFast: true
}
