node {
    def recipes = ['ubuntu14-ramses', 'centos7-ramses']

    for (recipe in recipes){
        stage "Launching ${recipe}"
        build job: 'ec3/ec3-generic-os-recipes', parameters: [string(name: 'OS', value: "${recipe}"), string(name: 'AUTH_FILE_ID', value: "${AUTH_FILE_ID}")]
    }
}
